# Generated by Django 2.1 on 2018-08-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(blank=True, choices=[('tvm', 'Thiruvananthapuram'), ('ptm', 'Pathanamthitta'), ('alp', 'Alappuzha'), ('ktm', 'Kottayam'), ('idk', 'Idukki'), ('mpm', 'Malappuram'), ('koz', 'Kozhikode'), ('wnd', 'Wayanad'), ('knr', 'Kannur'), ('ksr', 'Kasaragod'), ('pkd', 'Palakkad'), ('tcr', 'Thrissur'), ('ekm', 'Ernakulam'), ('kol', 'Kollam')], max_length=15, null=True, verbose_name='Districts - ജില്ല')),
                ('location', models.CharField(blank=True, max_length=500, null=True, verbose_name='Location - സ്ഥലം')),
                ('requestee', models.CharField(blank=True, max_length=100, null=True, verbose_name='Requestee - അപേക്ഷകന്\u200dറെ പേര്')),
                ('requestee_phone', models.CharField(max_length=10, verbose_name='Requestee Phone - അപേക്ഷകന്\u200dറെ ഫോണ്\u200d നമ്പര്\u200d')),
                ('needwater', models.BooleanField(default=False, verbose_name='Water - വെള്ളം')),
                ('needfood', models.BooleanField(default=False, verbose_name='Food - ഭക്ഷണം')),
                ('needcloth', models.BooleanField(default=False, verbose_name='Clothing - വസ്ത്രം')),
                ('needmed', models.BooleanField(default=False, verbose_name='Medicine - മരുന്നുകള്\u200d')),
                ('needtoilet', models.BooleanField(default=False, verbose_name='Toiletries - ശുചീകരണ സാമഗ്രികള്\u200d ')),
                ('needkit_util', models.BooleanField(default=False, verbose_name='Kitchen utensil - അടുക്കള സാമഗ്രികള്\u200d')),
                ('detailwater', models.CharField(blank=True, max_length=250, null=True, verbose_name='Details for required water - ആവശ്യമായ വെള്ളത്തിന്\u200dറെ വിവരങ്ങള്\u200d')),
                ('detailfood', models.CharField(blank=True, max_length=250, null=True, verbose_name='Details for required food - ആവശ്യമായ ഭക്ഷണത്തിന്\u200dറെ വിവരങ്ങള്\u200d')),
                ('detailcloth', models.CharField(blank=True, max_length=250, null=True, verbose_name='Details for required clothing - ആവശ്യമായ വസ്ത്രത്തിന്\u200dറെ വിവരങ്ങള്\u200d')),
                ('detailmed', models.CharField(blank=True, max_length=250, null=True, verbose_name='Details for required medicine - ആവശ്യമായ മരുന്നിന്\u200dറെ  വിവരങ്ങള്\u200d')),
                ('detailtoilet', models.CharField(blank=True, max_length=250, null=True, verbose_name='Details for required toiletries - ആവശ്യമായ  ശുചീകരണ സാമഗ്രികള്\u200d')),
                ('detailkit_util', models.CharField(blank=True, max_length=250, null=True, verbose_name='Details for required kitchen utensil - ആവശ്യമായ അടുക്കള സാമഗ്രികള്\u200d')),
                ('needothers', models.CharField(blank=True, max_length=500, null=True, verbose_name='Other needs - മറ്റു ആവശ്യങ്ങള്\u200d')),
                ('status', models.CharField(choices=[('new', 'New'), ('pro', 'In progess'), ('cmp', 'Completed')], default='new', max_length=10)),
                ('supply_details', models.CharField(blank=True, max_length=100, null=True)),
                ('dateadded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True, null=True)),
                ('request', models.ForeignKey(on_delete=None, to='mainapp.Request')),
            ],
        ),
        migrations.CreateModel(
            name='NewRequest',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('mainapp.request',),
        ),
    ]
