# Generated by Django 2.0.7 on 2018-08-16 16:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0002_assignedrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedrequest',
            name='request',
        ),
        migrations.RemoveField(
            model_name='assignedrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='request',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AssignedRequest',
        ),
    ]
