# Generated by Django 2.0.7 on 2018-08-16 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20180816_2232'),
        ('mainapp', '0003_auto_20180816_2201'),
    ]

    operations = [
    ]
