# Generated by Django 2.0.7 on 2018-08-16 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_request_updated_at'),
        ('mainapp', '0004_merge_20180816_2250'),
    ]

    operations = [
    ]
