# Generated by Django 2.0.7 on 2018-08-16 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_merge_20180816_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
