# Generated by Django 2.0.7 on 2018-08-17 00:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20180817_0452'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedRequest',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('mainapp.request',),
        ),
        migrations.AlterField(
            model_name='request',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Request'),
        ),
    ]
