# Generated by Django 2.0.7 on 2018-08-17 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20180817_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroundWorker',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('mainapp.volunteer',),
        ),
    ]
