# Generated by Django 2.0.7 on 2018-08-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_groundworker'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='panchayath',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Location'),
        ),
    ]
