# Generated by Django 2.0.7 on 2018-08-18 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_volunteer_panchayath'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Location')),
                ('level', models.IntegerField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.Service')),
            ],
        ),
        migrations.AddField(
            model_name='volunteer',
            name='area_willing_to_support',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='availability',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='is_smartphone',
            field=models.BooleanField(default=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='panchayath',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Panchayath'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='sevice_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_group', to='mainapp.Service'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='sevice_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_item', to='mainapp.Service'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='sevice_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_type', to='mainapp.Service'),
        ),
    ]
