# Generated by Django 2.0.7 on 2018-08-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20180818_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='resuced',
            field=models.BooleanField(default=False),
        ),
    ]
