# Generated by Django 2.0.7 on 2018-08-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20180818_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='services',
            field=models.ManyToManyField(to='mainapp.Service'),
        ),
    ]
