# Generated by Django 2.0.7 on 2018-08-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20180818_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name')),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('coordinates', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('no_of_people', models.IntegerField(blank=True, null=True)),
                ('degree_of_emergency', models.CharField(blank=True, max_length=200, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('help_required_immediatly', models.CharField(blank=True, max_length=100, null=True)),
                ('done', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
