# Generated by Django 2.0.7 on 2018-08-18 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_volunteer_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='level',
            new_name='service_group',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='parent',
            new_name='service_type',
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='sevice_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group', to='mainapp.Service'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='sevice_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item', to='mainapp.Service'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='sevice_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type', to='mainapp.Service'),
        ),
    ]
