# Generated by Django 2.0.7 on 2018-08-18 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_victim'),
        ('mainapp', '0012_request_resuced'),
    ]

    operations = [
    ]
