# Generated by Django 2.0.7 on 2018-08-19 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_merge_20180818_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='sevice_group',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='sevice_item',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='sevice_type',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='services',
            field=models.ManyToManyField(to='mainapp.Service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Service'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='is_smartphone',
            field=models.BooleanField(default=False),
        ),
    ]
