# Generated by Django 2.0.7 on 2018-08-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20180818_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='name',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='sevice_group',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='sevice_item',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='sevice_type',
        ),
        migrations.AddField(
            model_name='service',
            name='service_item',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
