# Generated by Django 2.0.7 on 2018-08-19 12:16

from django.db import migrations

def insert_services(apps, schema_editor):
    Service = apps.get_model('mainapp', 'Service')
    Service.objects.all().delete()

    Service.objects.create(name='Rescue', level=1, parent=None)
    Service.objects.create(name='In Site Rescue', level=2, parent=Service.objects.get(name='Rescue'))
    Service.objects.create(name='Boat', level=3, parent=Service.objects.get(name='In Site Rescue'))
    Service.objects.create(name='Heavy Vehicles', level=3, parent=Service.objects.get(name='In Site Rescue'))
    Service.objects.create(name='LMV', level=3, parent=Service.objects.get(name='In Site Rescue'))
    Service.objects.create(name='Volunteer', level=3, parent=Service.objects.get(name='In Site Rescue'))
    Service.objects.create(name='Relief Camps', level=2, parent=Service.objects.get(name='Rescue'))
    Service.objects.create(name='Medical', level=3, parent=Service.objects.get(name='Relief Camps'))
    Service.objects.create(name='Food', level=3, parent=Service.objects.get(name='Relief Camps'))
    Service.objects.create(name='Transportation', level=3, parent=Service.objects.get(name='Relief Camps'))
    Service.objects.create(name='Volunteer', level=3, parent=Service.objects.get(name='Relief Camps'))

    Service.objects.create(name='Food', level=1, parent=None)
    Service.objects.create(name='Store', level=2, parent=Service.objects.get(name='Food', level=1))
    Service.objects.create(name='Packed Food', level=3, parent=Service.objects.get(name='Store'))
    Service.objects.create(name='Raw Materials', level=3, parent=Service.objects.get(name='Store'))
    Service.objects.create(name='Drinking Water', level=3, parent=Service.objects.get(name='Store'))

    Service.objects.create(name='Transportation', level=2, parent=Service.objects.get(name='Food', level=1))
    Service.objects.create(name='Heavy Vehicle', level=3, parent=Service.objects.get(name='Transportation', level=2))
    Service.objects.create(name='LMV', level=3, parent=Service.objects.get(name='Transportation', level=2))
    Service.objects.create(name='Distribution', level=2, parent=Service.objects.get(name='Food', level=1))
    Service.objects.create(name='Volunteer', level=3, parent=Service.objects.get(name='Distribution'))

    Service.objects.create(name='Medical Assistance', level=1, parent=None)
    Service.objects.create(name='Doctor', level=2, parent=Service.objects.get(name='Medical Assistance'))
    Service.objects.create(name='Can work at Relief Camp', level=3, parent=Service.objects.get(name='Doctor'))
    Service.objects.create(name='Other', level=3, parent=Service.objects.get(name='Doctor'))
    Service.objects.create(name='Nursing Staff', level=2, parent=Service.objects.get(name='Medical Assistance'))
    Service.objects.create(name='Can work at Relief Camp', level=3, parent=Service.objects.get(name='Nursing Staff'))
    Service.objects.create(name='Pharmacist', level=2, parent=Service.objects.get(name='Medical Assistance'))
    Service.objects.create(name='Willing to Work at Relief Camp', level=3, parent=Service.objects.get(name='Pharmacist'))
    Service.objects.create(name='Medicine', level=2, parent=Service.objects.get(name='Medical Assistance'))
    Service.objects.create(name='Store', level=3, parent=Service.objects.get(name='Medicine'))
    Service.objects.create(name='Transportation', level=3, parent=Service.objects.get(name='Medicine'))
    Service.objects.create(name='Nursing', level=3, parent=Service.objects.get(name='Medicine'))
    Service.objects.create(name='Ambulance', level=2, parent=Service.objects.get(name='Medical Assistance'))
    Service.objects.create(name='With Life Supporting Instruments', level=3, parent=Service.objects.get(name='Ambulance'))
    Service.objects.create(name='Without Life Supporting Instruments', level=3, parent=Service.objects.get(name='Ambulance'))


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20180819_1652'),
    ]

    operations = [ migrations.RunPython(insert_services, reverse_code=migrations.RunPython.noop),]
