# Generated by Django 2.0.7 on 2018-08-19 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20180818_2115'),
        ('mainapp', '0015_insert_services'),
    ]

    operations = [
    ]
