# Generated by Django 2.1 on 2018-08-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_auto_20180815_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewRequest',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('mainapp.request',),
        ),
        migrations.AlterField(
            model_name='request',
            name='district',
            field=models.CharField(blank=True, choices=[('tvm', 'Thiruvananthapuram'), ('ptm', 'Pathanamthitta'), ('alp', 'Alappuzha'), ('ktm', 'Kottayam'), ('idk', 'Idukki'), ('mpm', 'Malappuram'), ('koz', 'Kozhikode'), ('wnd', 'Wayanad'), ('knr', 'Kannur'), ('ksr', 'Kasaragod'), ('pkd', 'Palakkad'), ('tcr', 'Thrissur'), ('ekm', 'Ernakulam'), ('kol', 'Kollam')], max_length=15, verbose_name='Districts - ജില്ല'),
        ),
        migrations.AlterField(
            model_name='request',
            name='location',
            field=models.CharField(blank=True, max_length=500, verbose_name='Location - സ്ഥലം'),
        ),
        migrations.AlterField(
            model_name='request',
            name='requestee',
            field=models.CharField(blank=True, max_length=100, verbose_name='Requestee - അപേക്ഷകന്\u200dറെ പേര്'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('pro', 'In progess'), ('cmp', 'Completed')], default='new', max_length=10),
        ),
    ]
